# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LOGIN(object):
    def setupUi(self, LOGIN):
        LOGIN.setObjectName("LOGIN")
        LOGIN.resize(423, 495)
        self.centralwidget = QtWidgets.QWidget(LOGIN)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginBackground = QtWidgets.QLabel(self.centralwidget)
        self.LoginBackground.setGeometry(QtCore.QRect(0, 0, 551, 601))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LoginBackground.setFont(font)
        self.LoginBackground.setText("")
        self.LoginBackground.setPixmap(QtGui.QPixmap("Icons/login3.png"))
        self.LoginBackground.setScaledContents(True)
        self.LoginBackground.setObjectName("LoginBackground")
        self.Logintext = QtWidgets.QLabel(self.centralwidget)
        self.Logintext.setGeometry(QtCore.QRect(100, 0, 371, 131))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Logintext.setFont(font)
        self.Logintext.setStyleSheet("")
        self.Logintext.setObjectName("Logintext")
        self.USERNAME = QtWidgets.QLineEdit(self.centralwidget)
        self.USERNAME.setGeometry(QtCore.QRect(210, 260, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.USERNAME.setFont(font)
        self.USERNAME.setStyleSheet("background:transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.USERNAME.setText("")
        self.USERNAME.setObjectName("USERNAME")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(50, 250, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(40, 310, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.PASSWORD = QtWidgets.QLineEdit(self.centralwidget)
        self.PASSWORD.setGeometry(QtCore.QRect(210, 320, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PASSWORD.setFont(font)
        self.PASSWORD.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.PASSWORD.setObjectName("PASSWORD")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(130, 390, 160, 48))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"border-radius: 24px;")
        self.login_button.setObjectName("login_button")
        self.user_id_label = QtWidgets.QLabel(self.centralwidget)
        self.user_id_label.setGeometry(QtCore.QRect(80, 190, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(23)
        self.user_id_label.setFont(font)
        self.user_id_label.setObjectName("user_id_label")
        self.USERID = QtWidgets.QLineEdit(self.centralwidget)
        self.USERID.setGeometry(QtCore.QRect(210, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.USERID.setFont(font)
        self.USERID.setStyleSheet("background:transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.USERID.setText("")
        self.USERID.setObjectName("USERID")
        self.Profile = QtWidgets.QLabel(self.centralwidget)
        self.Profile.setGeometry(QtCore.QRect(170, 100, 81, 81))
        self.Profile.setStyleSheet("background-color: transparent;\n"
"border-radius:25px;")
        self.Profile.setText("")
        self.Profile.setPixmap(QtGui.QPixmap("Icons/user_icon.png"))
        self.Profile.setScaledContents(True)
        self.Profile.setObjectName("Profile")
        LOGIN.setCentralWidget(self.centralwidget)

        self.retranslateUi(LOGIN)
        QtCore.QMetaObject.connectSlotsByName(LOGIN)

    def retranslateUi(self, LOGIN):
        _translate = QtCore.QCoreApplication.translate
        LOGIN.setWindowTitle(_translate("LOGIN", "MainWindow"))
        self.Logintext.setText(_translate("LOGIN", "<html><head/><body><p><span style=\" color:#55ffff;\">LOGIN TO JARVIS</span></p></body></html>"))
        self.username_label.setText(_translate("LOGIN", "<html><head/><body><p><span style=\" color:#00aaff;\">USERNAME</span></p></body></html>"))
        self.password_label.setText(_translate("LOGIN", "<html><head/><body><p><span style=\" color:#00aa00;\">PASSWORD</span></p></body></html>"))
        self.login_button.setText(_translate("LOGIN", "LOGIN"))
        self.user_id_label.setText(_translate("LOGIN", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">USER-ID</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LOGIN = QtWidgets.QMainWindow()
    ui = Ui_LOGIN()
    ui.setupUi(LOGIN)
    LOGIN.show()
    sys.exit(app.exec_())
